//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbTrailers
    {
        public int ID_Trailer { get; set; }
        public string Titulo { get; set; }
        public string Director { get; set; }
        public string Sipnosis { get; set; }
        public string Reparto { get; set; }
        public string Duracion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Trailer { get; set; }
        public byte[] img_logo { get; set; }
    }
}
